const mongoose = require("mongoose");

const connectDB = async () => {
    const uri = process.env.MONGODB_URI;
    const isPlaceholder = !uri || uri.includes("<user_name>") || uri.includes("<password>") || uri.includes("7udof89w.mongodb.net");

    // Add safe fallback for JWT_SECRET if missing or using standard placeholder
    if (!process.env.JWT_SECRET || process.env.JWT_SECRET.includes("openssl rand")) {
        if (process.env.NODE_ENV === 'production') {
            console.error("\n❌ FATAL SECURITY ERROR: JWT_SECRET is not configured in production!");
            console.error("❌ Do not deploy without setting a strong JWT_SECRET environment variable.");
            process.exit(1);
        } else {
            const crypto = require('crypto');
            const fs = require('fs');
            const path = require('path');
            
            const newSecret = crypto.randomBytes(32).toString('hex');
            process.env.JWT_SECRET = newSecret;
            
            const envPath = path.join(process.cwd(), '.env.local');
            try {
                fs.appendFileSync(envPath, `\n# Auto-generated by CreatorOS for local development\nJWT_SECRET=${newSecret}\n`);
                console.warn("\n✅ JWT_SECRET was missing. A secure random secret was automatically generated and saved to your .env.local file.\n");
            } catch (err) {
                console.warn("\n⚠️  JWT_SECRET missing. Auto-generated a temporary random secret, but failed to save to .env.local.\n");
            }
        }
    }

    if (isPlaceholder) {
        console.log("\n==================================================");
        console.log("⚠️  MongoDB URI not configured or using placeholder.");
        console.log("👉 CreatorOS is starting in MOCK DATABASE mode.");
        console.log("👉 Test user credentials: test@local.com / Password123!");
        console.log("==================================================\n");
        process.env.USE_MOCK_DB = "true";
        return;
    }

    try {
        await mongoose.connect(uri, {
            serverSelectionTimeoutMS: 3000
        });

        console.log("MongoDB Connected Successfully");
    } catch (error) {
        console.log("\n==================================================");
        console.log("MongoDB Connection Error:", error.message);
        console.log("👉 CreatorOS is falling back to MOCK DATABASE mode.");
        console.log("👉 Test user credentials: test@local.com / Password123!");
        console.log("==================================================\n");
        process.env.USE_MOCK_DB = "true";
    }
};

module.exports = connectDB;